In [14]:
import pandas as pd
import numpy as np
import rdflib


myont_ns = "http://www.co-ode.org/ontologies/ont.owl#"
foaf_ns = "http://xmlns.com/foaf/0.1/"
rdf_url = "https://Data#"


df = pd.read_csv("netflix_titles.csv")
df = df.rename(columns={'listed_in':'categorie'})
df = df.head(5)
print(np.array(df).shape)
print(df.head())

(5, 12)
    show_id     type                                    title  \
0  81145628    Movie  Norm of the North: King Sized Adventure
1  80117401    Movie               Jandino: Whatever it Takes
2  70234439  TV Show                       Transformers Prime
3  80058654  TV Show         Transformers: Robots in Disguise
4  80125979    Movie                             #realityhigh

                   director  \
0  Richard Finn, Tim Maltby
1                       NaN
2                       NaN
3                       NaN
4          Fernando Lebrija

                                                cast  \
0  Alan Marriott, Andrew Toth, Brian Dobson, Cole...
1                                   Jandino Asporaat
2  Peter Cullen, Sumalee Montano, Frank Welker, J...
3  Will Friedle, Darren Criss, Constance Zimmer, ...
4  Nesta Cooper, Kate Walsh, John Michael Higgins...

                                    country         date_added  release_year  \
0  United States, India, South Korea, China  September 9, 2019          2019
1                            United Kingdom  September 9, 2016          2016
2                             United States  September 8, 2018          2013
3                             United States  September 8, 2018          2016
4                             United States  September 8, 2017          2017

     rating  duration                           categorie  \
0     TV-PG    90 min  Children & Family Movies, Comedies
1     TV-MA    94 min                     Stand-Up Comedy
2  TV-Y7-FV  1 Season                            Kids' TV
3     TV-Y7  1 Season                            Kids' TV
4     TV-14    99 min                            Comedies

                                         description
0  Before planning an awesome wedding for his gra...
1  Jandino Asporaat riffs on the challenges of ra...
2  With the help of three human allies, the Autob...
3  When a prison ship crash unleashes hundreds of...
4  When nerdy high schooler Dani finally attracts...

In [4]:
"""
Cette fonction prend en paramètre une ligne de casting appartement au dataset sachant qu'ils peuvent être parcourus
en itérant sur df["cast"] et retourne une liste [(nom,prenom),(nom,prenom)...etc]
"""
def get_actors_names(cast):
    name = str(cast)
    names = name.split(",")
    l = []
    for i in names:
        n = i.split(" ")
        nn = []
        for i in n:
            if(i!=""):
                nn.append(i)
        l.append(nn)
    actors= []
    for i in l:
        actors.append( tuple([i[-1]," ".join(i[:-1])]))
    return actors

In [5]:
"""
Cette fonction ajouter un acteur.
Args : 
    - nom de l'acteur
    - prenom de l'acteur
    - un identifiant
Returns :
    Graphe contenant les tuples qui correspondent a l'ajout de l'acteur
"""
def add_actor(nom,prenom,id):
    graphe = rdflib.Graph()
    #Votre fonction
    return graphe

In [6]:
"""
Cette fonctions sert a ajouter le contenu d'une column automatiquement en donnant le nom de la colonne et celui
du concept correspondant a la colonne.
Pas besoin de la coder, regardez comment elle fonctionn et servez vous en.
Remarques : 
    - np.unique(L) renvoie une liste d'éléments unique d'un tableau numpy.
    
"""
def create_concept_from_col(df,column,concept_name):
    graphe = rdflib.Graph()
    concept_t = rdflib.URIRef(myont_ns+concept_name)
    graphe.add((concept_t,rdflib.RDF.term("type"),rdflib.OWL.term("Class")))
    arr = np.array(df[column]).astype(str)
    s = set()
    for i in np.unique(arr):
        L = i.replace(" ","").replace('.',"").replace('"',"").split(",")
        s.update(set(L))
    for i in s:
        graphe.add((rdflib.URIRef(rdf_url+i),rdflib.RDF.term("type"),concept_t))
    return graphe

In [7]:
f = open("film_db.owl","w")

graphe = rdflib.Graph()

concepts_columns = ["country","categorie","type"]
datatype_columns = ["description","title","release_year"]



for i in concepts_columns:
    graphe = graphe + create_concept_from_col(df,i,i)
    pass



actors_set = set()
for i in df["cast"]:
    actors = get_actors_names(i)
    actors_set.update(set(actors))

actors_set= list(actors_set)
print("Nombre d'acteurs : ",len(actors_set))

cpt=0
for actor in actors_set:
    cpt = cpt + 1
    print(cpt,"-",actor)
    graphe = graphe + add_actor(actor[0],actor[1],str(cpt))
    
graphe.serialize("film_db.owl","turtle")

Nombre d'acteurs :  11
1 - ('Howard', 'Cole')
2 - ('Kay', 'Maya')
3 - ('Tockar', 'Lee')
4 - ('Dobson', 'Brian')
5 - ('Holmes', 'Jonathan')
6 - ('Toth', 'Andrew')
7 - ('Dobson', 'Michael')
8 - ('Asporaat', 'Jandino')
9 - ('Durupt', 'Lisa')
10 - ('Marriott', 'Alan')
11 - ('Cameron', 'Jennifer')

In [8]:
!cat film_db.owl

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://Data#Children&FamilyMovies> a <http://www.co-ode.org/ontologies/ont.owl#categorie> .

<https://Data#China> a <http://www.co-ode.org/ontologies/ont.owl#country> .

<https://Data#Comedies> a <http://www.co-ode.org/ontologies/ont.owl#categorie> .

<https://Data#India> a <http://www.co-ode.org/ontologies/ont.owl#country> .

<https://Data#Movie> a <http://www.co-ode.org/ontologies/ont.owl#type> .

<https://Data#SouthKorea> a <http://www.co-ode.org/ontologies/ont.owl#country> .

<https://Data#Stand-UpComedy> a <http://www.co-ode.org/ontologies/ont.owl#categorie> .

<https://Data#UnitedKingdom> a <http://www.co-ode.org/ontologies/ont.owl#country> .

<https://Data#UnitedStates> a <http://www.co-ode.org/ontologies/ont.owl#country> .

<http://www.co-ode.org/ontologies/ont.owl#type> a <http://www.w3.org/2002/07/owl#Class> .

<http://www.co-ode.org/ontologies/ont.owl#categorie> a <http://www.w3.org/2002/07/owl#Class> .

<http://www.co-ode.org/ontologies/ont.owl#country> a <http://www.w3.org/2002/07/owl#Class> .

In [9]:
"""
Cette fonction ajouter une propriété a un film.
Args : 
    - nom de la propriété dans le vocab
    - valeur de la propriété
    - le film auquel il faut ajouter la propriété
Returns :
    Graphe contenant les tuples qui correspondent a l'ajout de la propriété au film
"""
def ajouter_attribut(id_film,nom_propriete,valeur_propriete):
    graphe = rdflib.Graph()
    #Votre fonction
    return graphe

In [11]:
"""
Parcourir le set de données et ajouter tout les films
Astuce : Executez cette fonction une fois pour voire ce que la boucle parcours et avisez ensuite
"""
def ajouter_films(df):
    graphe = rdflib.Graph()
    for i in datatype_columns:
        print("\n Remplissage de la colonne ",i)
        for idd,val in zip(df["show_id"],df[i]):
            print(".",end="")
            #Votre fonction
            print(idd,val)
    return graphe

In [62]:
graphe = graphe + ajouter_films(df)

 Remplissage de la colonne  description
..
 Remplissage de la colonne  title
..
 Remplissage de la colonne  release_year
..

In [63]:
graphe.serialize("film_db.owl","turtle")
!cat film_db.owl

@prefix ns1: <http://xmlns.com/foaf/0.1/> .
@prefix ns2: <http://www.co-ode.org/ontologies/ont.owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://Data#80117401> a ns2:Film ;
    ns2:description "Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of \"Sex on Fire\" in his comedy show." ;
    ns2:release_year 2016 ;
    ns2:title "Jandino: Whatever it Takes" .

<https://Data#81145628> a ns2:Film ;
    ns2:description "Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first." ;
    ns2:release_year 2019 ;
    ns2:title "Norm of the North: King Sized Adventure" .

<https://Data#A1> a ns2:Acteur ;
    ns1:familyName "Holmes" ;
    ns1:givenName "Jonathan" .

<https://Data#A10> a ns2:Acteur ;
    ns1:familyName "Asporaat" ;
    ns1:givenName "Jandino" .

<https://Data#A11> a ns2:Acteur ;
    ns1:familyName "Howard" ;
    ns1:givenName "Cole" .

<https://Data#A2> a ns2:Acteur ;
    ns1:familyName "Dobson" ;
    ns1:givenName "Michael" .

<https://Data#A3> a ns2:Acteur ;
    ns1:familyName "Marriott" ;
    ns1:givenName "Alan" .

<https://Data#A4> a ns2:Acteur ;
    ns1:familyName "Cameron" ;
    ns1:givenName "Jennifer" .

<https://Data#A5> a ns2:Acteur ;
    ns1:familyName "Dobson" ;
    ns1:givenName "Brian" .

<https://Data#A6> a ns2:Acteur ;
    ns1:familyName "Toth" ;
    ns1:givenName "Andrew" .

<https://Data#A7> a ns2:Acteur ;
    ns1:familyName "Durupt" ;
    ns1:givenName "Lisa" .

<https://Data#A8> a ns2:Acteur ;
    ns1:familyName "Tockar" ;
    ns1:givenName "Lee" .

<https://Data#A9> a ns2:Acteur ;
    ns1:familyName "Kay" ;
    ns1:givenName "Maya" .

<https://Data#Children&FamilyMovies> a ns2:categorie .

<https://Data#China> a ns2:country .

<https://Data#Comedies> a ns2:categorie .

<https://Data#India> a ns2:country .

<https://Data#Movie> a ns2:type .

<https://Data#SouthKorea> a ns2:country .

<https://Data#Stand-UpComedy> a ns2:categorie .

<https://Data#UnitedKingdom> a ns2:country .

<https://Data#UnitedStates> a ns2:country .

ns2:type a <http://www.w3.org/2002/07/owl#Class> .

ns2:categorie a <http://www.w3.org/2002/07/owl#Class> .

ns2:country a <http://www.w3.org/2002/07/owl#Class> .

ns2:Acteur a <http://www.w3.org/2002/07/owl#Class> .

In [12]:
def chercher_acteur(nom,prenom):
    requete = """
    prefix ns1: <http://xmlns.com/foaf/0.1/> 
    prefix ns2: <http://www.co-ode.org/ontologies/ont.owl#> 
    prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
    prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
    SELECT DISTINCT #identifiant acteur
    WHERE{
    #motifs contenant "%nom" et "%prenom"
    }
    """.replace("%nom",nom).replace("%prenom",prenom)
    res = graphe.query(requete)
    for i in res:
        return i[0]
chercher_acteur("Adam","Pally")

In [68]:
played_in = rdflib.URIRef(myont_ns+"played_in")
for acteur_list, ids in zip(df["cast"],df["show_id"]):
    film_r = rdflib.URIRef(rdf_url+str(ids))
    for nom,prenom in get_actors_names(acteur_list):
        acteur_r = chercher_acteur(prenom.replace('"','').replace('”',""),nom.replace('"','').replace('”',""))
        if(acteur_r != None):
            #Fonction qui ajoute l'acteur au film

In [69]:
graphe.serialize("film_db.owl","turtle")
!cat film_db.owl

@prefix ns1: <http://xmlns.com/foaf/0.1/> .
@prefix ns2: <http://www.co-ode.org/ontologies/ont.owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://Data#A1> a ns2:Acteur ;
    ns2:played_in <https://Data#81145628> ;
    ns1:familyName "Holmes" ;
    ns1:givenName "Jonathan" .

<https://Data#A10> a ns2:Acteur ;
    ns2:played_in <https://Data#80117401> ;
    ns1:familyName "Asporaat" ;
    ns1:givenName "Jandino" .

<https://Data#A11> a ns2:Acteur ;
    ns2:played_in <https://Data#81145628> ;
    ns1:familyName "Howard" ;
    ns1:givenName "Cole" .

<https://Data#A2> a ns2:Acteur ;
    ns2:played_in <https://Data#81145628> ;
    ns1:familyName "Dobson" ;
    ns1:givenName "Michael" .

<https://Data#A3> a ns2:Acteur ;
    ns2:played_in <https://Data#81145628> ;
    ns1:familyName "Marriott" ;
    ns1:givenName "Alan" .

<https://Data#A4> a ns2:Acteur ;
    ns2:played_in <https://Data#81145628> ;
    ns1:familyName "Cameron" ;
    ns1:givenName "Jennifer" .

<https://Data#A5> a ns2:Acteur ;
    ns2:played_in <https://Data#81145628> ;
    ns1:familyName "Dobson" ;
    ns1:givenName "Brian" .

<https://Data#A6> a ns2:Acteur ;
    ns2:played_in <https://Data#81145628> ;
    ns1:familyName "Toth" ;
    ns1:givenName "Andrew" .

<https://Data#A7> a ns2:Acteur ;
    ns2:played_in <https://Data#81145628> ;
    ns1:familyName "Durupt" ;
    ns1:givenName "Lisa" .

<https://Data#A8> a ns2:Acteur ;
    ns2:played_in <https://Data#81145628> ;
    ns1:familyName "Tockar" ;
    ns1:givenName "Lee" .

<https://Data#A9> a ns2:Acteur ;
    ns2:played_in <https://Data#81145628> ;
    ns1:familyName "Kay" ;
    ns1:givenName "Maya" .

<https://Data#Children&FamilyMovies> a ns2:categorie .

<https://Data#China> a ns2:country .

<https://Data#Comedies> a ns2:categorie .

<https://Data#India> a ns2:country .

<https://Data#Movie> a ns2:type .

<https://Data#SouthKorea> a ns2:country .

<https://Data#Stand-UpComedy> a ns2:categorie .

<https://Data#UnitedKingdom> a ns2:country .

<https://Data#UnitedStates> a ns2:country .

ns2:type a <http://www.w3.org/2002/07/owl#Class> .

<https://Data#80117401> a ns2:Film ;
    ns2:description "Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of \"Sex on Fire\" in his comedy show." ;
    ns2:release_year 2016 ;
    ns2:title "Jandino: Whatever it Takes" .

ns2:categorie a <http://www.w3.org/2002/07/owl#Class> .

ns2:country a <http://www.w3.org/2002/07/owl#Class> .

<https://Data#81145628> a ns2:Film ;
    ns2:description "Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first." ;
    ns2:release_year 2019 ;
    ns2:title "Norm of the North: King Sized Adventure" .

ns2:Acteur a <http://www.w3.org/2002/07/owl#Class> .

In [67]:
graphe.serialize("film_db.owl")
!cat film_db.owl

<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
   xmlns:ns1="http://xmlns.com/foaf/0.1/"
   xmlns:ns2="http://www.co-ode.org/ontologies/ont.owl#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
>
  <rdf:Description rdf:about="https://Data#81145628">
    <ns2:description>Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first.</ns2:description>
    <ns2:title>Norm of the North: King Sized Adventure</ns2:title>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Film"/>
    <ns2:release_year rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">2019</ns2:release_year>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.co-ode.org/ontologies/ont.owl#Acteur">
    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A1">
    <ns1:givenName>Jonathan</ns1:givenName>
    <ns2:played_in rdf:resource="https://Data#81145628"/>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
    <ns1:familyName>Holmes</ns1:familyName>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A11">
    <ns1:givenName>Cole</ns1:givenName>
    <ns1:familyName>Howard</ns1:familyName>
    <ns2:played_in rdf:resource="https://Data#81145628"/>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A2">
    <ns2:played_in rdf:resource="https://Data#81145628"/>
    <ns1:familyName>Dobson</ns1:familyName>
    <ns1:givenName>Michael</ns1:givenName>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A6">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
    <ns1:familyName>Toth</ns1:familyName>
    <ns1:givenName>Andrew</ns1:givenName>
    <ns2:played_in rdf:resource="https://Data#81145628"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#80117401">
    <ns2:title>Jandino: Whatever it Takes</ns2:title>
    <ns2:description>Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of "Sex on Fire" in his comedy show.</ns2:description>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Film"/>
    <ns2:release_year rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">2016</ns2:release_year>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A7">
    <ns1:familyName>Durupt</ns1:familyName>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
    <ns2:played_in rdf:resource="https://Data#81145628"/>
    <ns1:givenName>Lisa</ns1:givenName>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#China">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#country"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A3">
    <ns1:givenName>Alan</ns1:givenName>
    <ns2:played_in rdf:resource="https://Data#81145628"/>
    <ns1:familyName>Marriott</ns1:familyName>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#Comedies">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#categorie"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#Children&amp;FamilyMovies">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#categorie"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A10">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
    <ns1:familyName>Asporaat</ns1:familyName>
    <ns2:played_in rdf:resource="https://Data#80117401"/>
    <ns1:givenName>Jandino</ns1:givenName>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A8">
    <ns1:givenName>Lee</ns1:givenName>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
    <ns2:played_in rdf:resource="https://Data#81145628"/>
    <ns1:familyName>Tockar</ns1:familyName>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.co-ode.org/ontologies/ont.owl#categorie">
    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A5">
    <ns1:givenName>Brian</ns1:givenName>
    <ns2:played_in rdf:resource="https://Data#81145628"/>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
    <ns1:familyName>Dobson</ns1:familyName>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A9">
    <ns2:played_in rdf:resource="https://Data#81145628"/>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
    <ns1:givenName>Maya</ns1:givenName>
    <ns1:familyName>Kay</ns1:familyName>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#Movie">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#type"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#A4">
    <ns1:givenName>Jennifer</ns1:givenName>
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#Acteur"/>
    <ns1:familyName>Cameron</ns1:familyName>
    <ns2:played_in rdf:resource="https://Data#81145628"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#UnitedStates">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#country"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#India">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#country"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#Stand-UpComedy">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#categorie"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#UnitedKingdom">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#country"/>
  </rdf:Description>
  <rdf:Description rdf:about="https://Data#SouthKorea">
    <rdf:type rdf:resource="http://www.co-ode.org/ontologies/ont.owl#country"/>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.co-ode.org/ontologies/ont.owl#country">
    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.co-ode.org/ontologies/ont.owl#type">
    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
  </rdf:Description>
</rdf:RDF>